variables:
  CI_DOCKERHUB_IMAGE: huncrys/znc
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/docker-publish@~latest
    inputs:
      licenses: Apache-2.0
