variables:
  CI_DOCKERHUB_IMAGE: huncrys/znc
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/oci-publish@8
    inputs:
      licenses: Apache-2.0
      platforms:
        - linux/amd64
        - linux/386
        - linux/arm64
        - linux/arm/v7
        - linux/arm/v6
        - linux/ppc64le
        - linux/riscv64
        - linux/s390x
