spec:
  inputs:
    no-cache:
      type: boolean
      default: false
      description: Whether to disable the build cache when building the image.
---
variables:
  CI_DOCKERHUB_IMAGE: huncrys/znc
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/hadolint@11
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/oci-publish@11
    inputs:
      licenses: Apache-2.0
      platforms:
        - linux/amd64
        - linux/arm64
      registry-cache: true
      no-cache: $[[ inputs.no-cache ]]
